const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const context={window:{},crypto:require('node:crypto').webcrypto,console};
vm.createContext(context);
for(const file of ['cards.js','core.js','storage.js','card-renderer.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../scripts',file),'utf8'),context);
const T=context.window.TikaTarot;
const plain=x=>JSON.parse(JSON.stringify(x));
function memory(initial={}){const m=new Map(Object.entries(initial));return{getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};}
function reading(){const s=T.createSession('测试问题','situation-obstacle-advice',true);s.phase='selecting';[0,5,21].forEach(i=>T.select(s,i));[2,0,1].forEach(i=>T.reveal(s,i));return T.toReading(s);}
test('22 unique cards, original content, and 22 distinct motifs',()=>{
 assert.equal(T.cards.length,22);assert.equal(new Set(T.cards.map(c=>c.id)).size,22);
 assert.equal(new Set(T.cards.map(c=>T.cardSVG(c))).size,22);
 for(const c of T.cards)for(const side of ['upright','reversed']){assert.ok(c[side].meaning.length>=60);assert.ok(c[side].meaning.length<=110);assert.ok(c[side].reflection.endsWith('？'));}
});
test('rejection sampling excludes biased tail',()=>{const samples=[0xffffffff,21];assert.equal(T.randomInt(22,()=>samples.shift()),21);assert.equal(samples.length,0);assert.throws(()=>T.randomInt(0));});
test('shuffle preserves full deck and has deterministic injected source',()=>{const d=T.shuffle(T.cards,false,()=>0);assert.equal(d.length,22);assert.equal(new Set(d.map(x=>x.cardId)).size,22);assert.equal(d[0].cardId,'card-01');assert.equal(d[21].cardId,'card-00');assert.ok(d.every(c=>!c.reversed));assert.ok(T.shuffle(T.cards,true,()=>1).every(c=>c.reversed));});
test('selection prevents repeats and overdraw; reveal is idempotent and independent of order',()=>{const s=T.createSession('','situation-obstacle-advice',false);assert.equal(T.select(s,0),false);s.phase='selecting';assert.equal(T.select(s,-1),false);assert.equal(T.select(s,0),true);assert.equal(T.select(s,0),false);assert.equal(T.reveal(s,0),false);T.select(s,1);T.select(s,2);assert.equal(T.select(s,3),false);const frozen=JSON.stringify(s.deck);assert.equal(T.reveal(s,2),true);assert.equal(T.reveal(s,2),false);assert.equal(T.reveal(s,-1),false);T.reveal(s,0);T.reveal(s,1);assert.equal(s.phase,'complete');assert.equal(JSON.stringify(s.deck),frozen);assert.equal(T.toReading(s).cards.length,3);});
test('single-card completion and question fallback',()=>{const s=T.createSession(' ','single',false);s.phase='selecting';T.select(s,0);T.reveal(s,0);assert.equal(s.phase,'complete');assert.equal(s.question,'此刻的指引');assert.equal(T.toReading(s).cards.length,1);});
test('storage saves one ID, reloads notes and retains interpretation snapshots',()=>{const m=memory(),s=T.createStore(()=>m),r=reading();assert.equal(s.save(r),true);s.save({...r,note:'<script>只作为文字</script>'});assert.equal(s.data.readings.length,1);const reload=T.createStore(()=>m);assert.equal(reload.data.readings[0].note,'<script>只作为文字</script>');assert.deepEqual(plain(reload.data.readings[0].cards),plain(r.cards));});
test('storage denial and quota failure keep data available for export',()=>{const s=T.createStore(()=>{throw Error('denied')});s.save(reading());assert.equal(s.mode,'memory');assert.equal(s.export().readings.length,1);const m=memory(),p=T.createStore(()=>m);m.setItem=()=>{throw Error('quota')};assert.equal(p.save(reading()),false);assert.equal(p.dirty,true);assert.equal(p.export().readings.length,1);});
test('corrupt or future stored data is preserved, not overwritten',()=>{for(const raw of ['{broken',JSON.stringify({schemaVersion:99})]){const m=memory({'tika-tarot:v1':raw}),s=T.createStore(()=>m);assert.equal(s.mode,'memory');s.save(reading());assert.equal(m.getItem('tika-tarot:v1'),raw);assert.equal(s.raw,raw);}});
test('backup import is duplicate-safe; conflicts get a new ID',()=>{const a=T.createStore(()=>memory()),r=reading();a.save(r);const backup=a.export(),b=T.createStore(()=>memory());assert.equal(b.merge(backup).added,1);assert.equal(b.merge(backup).skipped,1);const changed=plain(backup);changed.readings[0].note='另一条笔记';assert.equal(b.merge(changed).conflicts,1);assert.equal(b.data.readings.length,2);assert.notEqual(b.data.readings[0].id,b.data.readings[1].id);assert.equal(b.data.readings[0].note,'');});
test('malformed imports reject without changing existing data',()=>{const s=T.createStore(()=>memory());s.save(reading());const original=JSON.stringify(s.data);const mutations=[b=>b.schemaVersion=2,b=>b.readings[0].cards[1].cardId=b.readings[0].cards[0].cardId,b=>b.readings[0].cards[0].reversed='false',b=>b.readings[0].cards[0].positionId='bad',b=>b.readings[0].note='x'.repeat(2001),b=>b.readings[0].spreadId='__proto__'];for(const change of mutations){const b=s.export();change(b);assert.throws(()=>s.merge(b));assert.equal(JSON.stringify(s.data),original);}});
test('external window changes cannot be silently overwritten',()=>{const m=memory(),a=T.createStore(()=>m),b=T.createStore(()=>m);a.save(reading());const external=m.getItem('tika-tarot:v1');assert.equal(b.save(reading()),false);assert.equal(m.getItem('tika-tarot:v1'),external);assert.equal(b.export().readings.length,1);});
test('runtime uses only local resources and classic scripts',()=>{const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.ok(!html.includes('type="module"'));for(const src of html.matchAll(/(?:src|href)="([^"]+)"/g)){if(src[1].startsWith('data:')||src[1].startsWith('#'))continue;assert.ok(!/^https?:/.test(src[1]));assert.ok(fs.existsSync(path.join(root,src[1])));}for(const f of fs.readdirSync(path.join(root,'scripts'))){const code=fs.readFileSync(path.join(root,'scripts',f),'utf8');assert.ok(!/\bfetch\s*\(|XMLHttpRequest|WebSocket|https?:\/\//.test(code.replaceAll('http://www.w3.org/2000/svg','')));}});
